server:
  port: 8080

spring:
  datasource:
    name: demo  #数据库名
    url: jdbc:mysql://localhost:3306/demo #url
    username: root  #用户名
    password: dzc@2231  #密码
    driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动